site_name: Creación de Sitios Usando Diferentes Temas en HUGO y MKDOCS
site_url: https://activida3.iaw
nav:
  - HOME: index.md
  - Hugo_ananke: Hugo_anakle.md
  - Hugo_walden:  Hugo_walden.md
  - MKDOCS: mkdocs.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange


copyright: Copyright &copy; 2024 RRH
